#!/usr/bin/env python3
"""
Interactive configuration wizard for ZirconOSAero build.conf.
Run via: make configure  (or: python3 scripts/configure.py)
"""

import os
import sys
import re

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD_CONF = os.path.join(PROJECT_ROOT, "build.conf")

def effective_setting(setting, values):
    _ = values
    return setting


SETTINGS = [
    {
        "key": "ARCH",
        "prompt": "Target architecture",
        "options": ["x86_64", "aarch64", "loongarch64", "riscv64", "mips64el"],
        "default": "x86_64",
    },
    {
        "key": "BOOT_METHOD",
        "prompt": "Boot method",
        "options": ["uefi", "mbr"],
        "default": "uefi",
    },
    {
        "key": "BOOTLOADER",
        "prompt": "Bootloader (ZBM only in this tree)",
        "options": ["zbm"],
        "default": "zbm",
    },
    {
        "key": "DESKTOP",
        "prompt": "Desktop theme",
        "options": ["aero", "none"],
        "default": "aero",
    },
    {
        "key": "OPTIMIZE",
        "prompt": "Build optimization",
        "options": ["Debug", "ReleaseSafe", "ReleaseFast", "ReleaseSmall"],
        "default": "Debug",
    },
    {
        "key": "RESOLUTION",
        "prompt": "Display resolution",
        "options": ["1024x768x32", "1280x800x32", "1280x1024x32", "1920x1080x32"],
        "default": "1024x768x32",
    },
    {
        "key": "QEMU_MEM",
        "prompt": "QEMU memory",
        "options": ["256M", "512M", "1G", "2G"],
        "default": "512M",
    },
]


def read_current_conf():
    """Read current build.conf values."""
    values = {}
    if os.path.exists(BUILD_CONF):
        with open(BUILD_CONF) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    m = re.match(r"^(\w+)\s*=\s*(.+)$", line)
                    if m:
                        values[m.group(1)] = m.group(2).strip()
    return values


def prompt_choice(setting, current_val):
    """Prompt user for a single setting."""
    key = setting["key"]
    options = setting["options"]
    default = current_val if current_val in options else setting["default"]

    print(f"\n  {setting['prompt']} ({key}):")
    for i, opt in enumerate(options):
        marker = " *" if opt == default else ""
        print(f"    {i + 1}) {opt}{marker}")

    while True:
        raw = input(f"  Choose [1-{len(options)}] (default: {default}): ").strip()
        if not raw:
            return default
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(options):
                return options[idx]
        except ValueError:
            if raw in options:
                return raw
        print(f"  Invalid choice. Enter 1-{len(options)} or press Enter for default.")


def write_conf(values):
    """Write build.conf with the given values."""
    if values.get("ARCH") == "loongarch64":
        values = dict(values)
        values["BOOTLOADER"] = "zbm"

    lines = [
        "# ZirconOS Build Configuration",
        "# Generated by: make configure",
        "# Edit this file or re-run 'make configure' to change settings.",
        "",
    ]
    for setting in SETTINGS:
        key = setting["key"]
        val = values.get(key, setting["default"])
        lines.append(f"{key} = {val}")

    # Preserve extra keys not in SETTINGS
    extra_keys = {"ENABLE_IDT", "DEBUG_LOG"}
    for k in extra_keys:
        if k in values:
            lines.append(f"{k} = {values[k]}")

    lines.append("")
    with open(BUILD_CONF, "w") as f:
        f.write("\n".join(lines))


def main():
    print("╔══════════════════════════════════════════╗")
    print("║   ZirconOS Build Configuration Wizard    ║")
    print("╚══════════════════════════════════════════╝")

    current = read_current_conf()

    if current:
        print("\n  Current configuration:")
        for s in SETTINGS:
            k = s["key"]
            v = current.get(k, s["default"])
            print(f"    {k:15s} = {v}")

    values = dict(current)
    for setting in SETTINGS:
        eff = effective_setting(setting, values)
        cur = current.get(setting["key"], eff["default"])
        values[setting["key"]] = prompt_choice(eff, cur)

    print("\n  New configuration:")
    for s in SETTINGS:
        k = s["key"]
        print(f"    {k:15s} = {values[k]}")

    confirm = input("\n  Write to build.conf? [Y/n]: ").strip().lower()
    if confirm in ("", "y", "yes"):
        write_conf(values)
        print(f"\n  Written: {BUILD_CONF}")
        print("  Run 'make' to build with the new configuration.")
    else:
        print("  Cancelled.")


if __name__ == "__main__":
    main()
