#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Sync resolution from build.conf (or ZIRCON_RESOLUTION env) into configs + generated headers.

Priority:
  1) Environment ZIRCON_RESOLUTION=WxHxdepth (only when `make RESOLUTION=…` or exported RESOLUTION — Makefile 默认不传，以免掩盖 build.conf)
  2) build.conf 中首个未注释行 RESOLUTION=WxHxdepth

Writes:
  - config/*.conf and src/config/*.conf  ([resolution], boot grub/uefi, system [display] default_*)
  - build/tmp/zircon_pref_fb.h          (LoongArch C EFI stub #include)
  - build/tmp/kernel_pref_fb_wh.txt     (two lines: width, height)

Zig `build.zig`：`build.conf` RESOLUTION 优先于 kernel_pref_fb_wh.txt；可选 `-Dzbm_preferred_fb_*` 覆盖。
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD_CONF = ROOT / "build.conf"
TMP_DIR = ROOT / "build" / "tmp"
PREF_FB_H = TMP_DIR / "zircon_pref_fb.h"
KERNEL_PREF_FB_WH = TMP_DIR / "kernel_pref_fb_wh.txt"
DESKTOP_PATHS = (ROOT / "config" / "desktop.conf", ROOT / "src" / "config" / "desktop.conf")
BOOT_PATHS = (ROOT / "config" / "boot.conf", ROOT / "src" / "config" / "boot.conf")
SYSTEM_PATHS = (ROOT / "config" / "system.conf", ROOT / "src" / "config" / "system.conf")


def parse_resolution_triple(s: str) -> tuple[int, int, int]:
    """Parse '1920x1080x32' or ' 1920 x 1080 x 32 '."""
    m = re.match(r"^\s*(\d+)\s*x\s*(\d+)\s*x\s*(\d+)\s*$", s.strip(), re.I)
    if not m:
        raise ValueError(f"expected WxHxdepth, got: {s!r}")
    w, h, d = int(m.group(1)), int(m.group(2)), int(m.group(3))
    if w <= 0 or h <= 0 or d <= 0:
        raise ValueError(f"invalid dimensions: {w}x{h}x{d}")
    return w, h, d


def parse_resolution_from_build_conf(text: str) -> tuple[int, int, int]:
    m = re.search(r"^\s*RESOLUTION\s*=\s*(\d+)x(\d+)x(\d+)", text, re.MULTILINE)
    if m:
        return int(m.group(1)), int(m.group(2)), int(m.group(3))
    return 1920, 1080, 32


def resolve_wh_d() -> tuple[int, int, int]:
    env = os.environ.get("ZIRCON_RESOLUTION", "").strip()
    if env:
        return parse_resolution_triple(env)
    if BUILD_CONF.is_file():
        return parse_resolution_from_build_conf(BUILD_CONF.read_text(encoding="utf-8"))
    raise RuntimeError(
        "Missing build.conf and ZIRCON_RESOLUTION is unset. "
        "Set RESOLUTION in build.conf or: ZIRCON_RESOLUTION=1920x1080x32 python3 scripts/sync_resolution_config.py"
    )


def patch_desktop(content: str, w: int, h: int) -> str:
    lines = content.splitlines(keepends=True)
    in_res = False
    out: list[str] = []
    for line in lines:
        if line.strip().startswith("[") and line.strip() != "[resolution]":
            in_res = False
        if line.strip() == "[resolution]":
            in_res = True
        if in_res:
            if re.match(r"^\s*width\s*=", line):
                line = re.sub(r"=\s*\d+", f"= {w}", line, count=1)
            elif re.match(r"^\s*height\s*=", line):
                line = re.sub(r"=\s*\d+", f"= {h}", line, count=1)
        out.append(line)
    return "".join(out)


def patch_boot(content: str, w: int, h: int, d: int) -> str:
    gfx = f"{w}x{h}x{d}"
    uefi_res = f"{w}x{h}"
    section: str | None = None
    out: list[str] = []
    for line in content.splitlines(keepends=True):
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            section = s[1:-1].strip().lower()
        elif section == "grub" and re.match(r"^\s*gfxmode\s*=", line):
            line = re.sub(r"=\s*\S+", f"= {gfx}", line, count=1)
        elif section == "uefi" and re.match(r"^\s*resolution\s*=", line):
            line = re.sub(r"=\s*\S+", f"= {uefi_res}", line, count=1)
        out.append(line)
    return "".join(out)


def patch_system_display(content: str, w: int, h: int, d: int) -> str:
    """Sync [display] default_width / default_height / default_bpp with RESOLUTION (embedded system.conf)."""
    lines = content.splitlines(keepends=True)
    in_display = False
    out: list[str] = []
    for line in lines:
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            in_display = s.lower() == "[display]"
        elif in_display:
            if re.match(r"^\s*default_width\s*=", line):
                line = re.sub(r"=\s*\d+", f"= {w}", line, count=1)
            elif re.match(r"^\s*default_height\s*=", line):
                line = re.sub(r"=\s*\d+", f"= {h}", line, count=1)
            elif re.match(r"^\s*default_bpp\s*=", line):
                line = re.sub(r"=\s*\d+", f"= {d}", line, count=1)
        out.append(line)
    return "".join(out)


def write_pref_fb_header(path: Path, w: int, h: int, d: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""/* Auto-generated by scripts/sync_resolution_config.py — do not edit */
#pragma once
#define ZIRCON_PREF_FB_WIDTH {w}U
#define ZIRCON_PREF_FB_HEIGHT {h}U
#define ZIRCON_PREF_FB_DEPTH {d}U
""",
        encoding="utf-8",
    )


def write_kernel_pref_fb_wh(path: Path, w: int, h: int) -> None:
    """供 build.zig 解析；与 C 头、嵌入 desktop 同源。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{w}\n{h}\n", encoding="ascii")


def main() -> int:
    try:
        w, h, d = resolve_wh_d()
    except (ValueError, RuntimeError) as e:
        print(str(e), file=sys.stderr)
        return 1

    for p in DESKTOP_PATHS:
        if not p.is_file():
            print(f"Missing {p}", file=sys.stderr)
            return 1
    for p in BOOT_PATHS:
        if not p.is_file():
            print(f"Missing {p}", file=sys.stderr)
            return 1
    for p in SYSTEM_PATHS:
        if not p.is_file():
            print(f"Missing {p}", file=sys.stderr)
            return 1

    write_pref_fb_header(PREF_FB_H, w, h, d)
    write_kernel_pref_fb_wh(KERNEL_PREF_FB_WH, w, h)

    for p in DESKTOP_PATHS:
        p.write_text(patch_desktop(p.read_text(encoding="utf-8"), w, h), encoding="utf-8")
    for p in BOOT_PATHS:
        p.write_text(patch_boot(p.read_text(encoding="utf-8"), w, h, d), encoding="utf-8")
    for p in SYSTEM_PATHS:
        p.write_text(patch_system_display(p.read_text(encoding="utf-8"), w, h, d), encoding="utf-8")

    src = "ZIRCON_RESOLUTION" if os.environ.get("ZIRCON_RESOLUTION", "").strip() else "build.conf"
    print(
        f"Synced resolution {w}x{h}x{d} (from {src}) → desktop/boot/system.conf + "
        f"{PREF_FB_H.relative_to(ROOT)} + {KERNEL_PREF_FB_WH.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
