//! SPDX-License-Identifier: MIT OR Apache-2.0
//!
//! ZirconOSAero — host-only build tool
//! Purpose: decode PNG wallpapers, downscale, emit raw RGBA + manifest.zig for kernel @embedFile.
//!
//! Run by build.zig (see wallpaper_gen output directory argument).

const std = @import("std");
const zigimg = @import("zigimg");

const max_tex_w: usize = 640;
const max_tex_h: usize = 360;

/// Preset order must match `wallpaper_bitmap.zig` and `renderer_aero.wallpaper_preset_count`.
const inputs = [_][]const u8{
    "src/desktop/aero/resources/wallpapers/Landscapes/zircon_harmony.png",
    "src/desktop/aero/resources/wallpapers/Nature/zircon_default.png",
    "src/desktop/aero/resources/wallpapers/Architecture/zircon_crystal.png",
    "src/desktop/aero/resources/wallpapers/Landscapes/zircon_aurora.png",
    "src/desktop/aero/resources/wallpapers/Characters/zircon_characters.png",
    "src/desktop/aero/resources/wallpapers/Nature/zircon_nature.png",
    "src/desktop/aero/resources/wallpapers/Scenes/zircon_scenes.png",
    "src/desktop/aero/resources/wallpapers/Landscapes/zircon_landscapes.png",
    "src/desktop/aero/resources/wallpapers/Architecture/zircon_architecture.png",
    "src/desktop/aero/resources/wallpapers/Nature/zircon_ocean.png",
    "src/desktop/aero/resources/wallpapers/Scenes/zircon_nebula.png",
    "src/desktop/aero/resources/wallpapers/Landscapes/zircon_landscape.png",
};

fn scaleDims(sw: usize, sh: usize) struct { usize, usize } {
    if (sw <= max_tex_w and sh <= max_tex_h) return .{ sw, sh };
    const sx = @as(f64, @floatFromInt(max_tex_w)) / @as(f64, @floatFromInt(sw));
    const sy = @as(f64, @floatFromInt(max_tex_h)) / @as(f64, @floatFromInt(sh));
    const s = @min(sx, sy);
    const nw = @max(1, @as(usize, @intFromFloat(@ceil(@as(f64, @floatFromInt(sw)) * s))));
    const nh = @max(1, @as(usize, @intFromFloat(@ceil(@as(f64, @floatFromInt(sh)) * s))));
    return .{ nw, nh };
}

fn nearestResize(src: []const u8, sw: usize, sh: usize, dw: usize, dh: usize, dst: []u8) void {
    std.debug.assert(src.len >= sw * sh * 4);
    std.debug.assert(dst.len >= dw * dh * 4);
    var y: usize = 0;
    while (y < dh) : (y += 1) {
        const sy = @min((y * sh) / @max(dh, 1), sh -| 1);
        var x: usize = 0;
        while (x < dw) : (x += 1) {
            const sx = @min((x * sw) / @max(dw, 1), sw -| 1);
            const si = (sy * sw + sx) * 4;
            const di = (y * dw + x) * 4;
            @memcpy(dst[di..][0..4], src[si..][0..4]);
        }
    }
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    const args = try std.process.argsAlloc(alloc);
    defer std.process.argsFree(alloc, args);
    if (args.len < 2) {
        std.debug.print("usage: wallpaper_embed <output_dir>\n", .{});
        return error.BadArgs;
    }
    const out_abs = args[1];

    var out_dir = try std.fs.openDirAbsolute(out_abs, .{});
    defer out_dir.close();

    var read_buf: [1 << 23]u8 = undefined;

    var manifest: std.ArrayList(u8) = .{};
    defer manifest.deinit(alloc);
    const mw = manifest.writer(alloc);

    try mw.print(
        \\// SPDX-License-Identifier: MIT OR Apache-2.0
        \\//! AUTO-GENERATED by tools/wallpaper_embed.zig — do not edit.
        \\
        \\pub const preset_count: usize = {d};
        \\
        \\
    , .{inputs.len});

    for (inputs, 0..) |rel_path, i| {
        var img = try zigimg.Image.fromFilePath(alloc, rel_path, &read_buf);
        defer img.deinit(alloc);
        try img.convert(alloc, zigimg.PixelFormat.rgba32);
        const raw = img.rawBytes();
        const sw = img.width;
        const sh = img.height;
        if (sw == 0 or sh == 0) return error.EmptyImage;

        const nw, const nh = scaleDims(sw, sh);
        const out_pixels = try alloc.alloc(u8, nw * nh * 4);
        defer alloc.free(out_pixels);
        nearestResize(raw, sw, sh, nw, nh, out_pixels);

        const rgba_name = try std.fmt.allocPrint(alloc, "preset{d}.rgba", .{i});
        defer alloc.free(rgba_name);
        try out_dir.writeFile(.{ .sub_path = rgba_name, .data = out_pixels });

        try mw.print("pub const p{d}_w: u32 = {d};\n", .{ i, nw });
        try mw.print("pub const p{d}_h: u32 = {d};\n", .{ i, nh });
        try mw.print("pub const p{d} = @embedFile(\"preset{d}.rgba\");\n\n", .{ i, i });
    }

    try out_dir.writeFile(.{ .sub_path = "wallpaper_embed_manifest.zig", .data = manifest.items });
}
