// SPDX-License-Identifier: MIT OR Apache-2.0
//! AUTO-GENERATED by tools/svg_to_rgba.zig — do not edit manually.
//! This file contains pre-rasterized RGBA bitmaps for all SVG icons/logo/start_orb.

pub const icon_count = 32;
pub const cursor_count = 14;

pub const logo_w: u32 = 64;
pub const logo_h: u32 = 64;
pub const logo = @embedFile("logo.rgba");

pub const start_orb_w: u32 = 64;
pub const start_orb_h: u32 = 64;
pub const start_orb = @embedFile("start_orb.rgba");

pub const ic_01_computer_w: u32 = 64;
pub const ic_01_computer_h: u32 = 64;
pub const ic_01_computer = @embedFile("ic_01_computer.rgba");

pub const ic_02_documents_w: u32 = 64;
pub const ic_02_documents_h: u32 = 64;
pub const ic_02_documents = @embedFile("ic_02_documents.rgba");

pub const ic_03_recycle_bin_w: u32 = 64;
pub const ic_03_recycle_bin_h: u32 = 64;
pub const ic_03_recycle_bin = @embedFile("ic_03_recycle_bin.rgba");

pub const ic_04_terminal_w: u32 = 64;
pub const ic_04_terminal_h: u32 = 64;
pub const ic_04_terminal = @embedFile("ic_04_terminal.rgba");

pub const ic_05_network_w: u32 = 64;
pub const ic_05_network_h: u32 = 64;
pub const ic_05_network = @embedFile("ic_05_network.rgba");

pub const ic_06_browser_w: u32 = 64;
pub const ic_06_browser_h: u32 = 64;
pub const ic_06_browser = @embedFile("ic_06_browser.rgba");

pub const ic_07_settings_w: u32 = 64;
pub const ic_07_settings_h: u32 = 64;
pub const ic_07_settings = @embedFile("ic_07_settings.rgba");

pub const ic_08_calculator_w: u32 = 64;
pub const ic_08_calculator_h: u32 = 64;
pub const ic_08_calculator = @embedFile("ic_08_calculator.rgba");

pub const ic_09_text_editor_w: u32 = 64;
pub const ic_09_text_editor_h: u32 = 64;
pub const ic_09_text_editor = @embedFile("ic_09_text_editor.rgba");

pub const ic_10_pictures_w: u32 = 64;
pub const ic_10_pictures_h: u32 = 64;
pub const ic_10_pictures = @embedFile("ic_10_pictures.rgba");

pub const ic_11_music_w: u32 = 64;
pub const ic_11_music_h: u32 = 64;
pub const ic_11_music = @embedFile("ic_11_music.rgba");

pub const ic_12_folder_w: u32 = 64;
pub const ic_12_folder_h: u32 = 64;
pub const ic_12_folder = @embedFile("ic_12_folder.rgba");

pub const ic_13_control_panel_w: u32 = 64;
pub const ic_13_control_panel_h: u32 = 64;
pub const ic_13_control_panel = @embedFile("ic_13_control_panel.rgba");

pub const ic_14_file_w: u32 = 64;
pub const ic_14_file_h: u32 = 64;
pub const ic_14_file = @embedFile("ic_14_file.rgba");

pub const ic_15_user_w: u32 = 64;
pub const ic_15_user_h: u32 = 64;
pub const ic_15_user = @embedFile("ic_15_user.rgba");

pub const ic_16_lock_w: u32 = 64;
pub const ic_16_lock_h: u32 = 64;
pub const ic_16_lock = @embedFile("ic_16_lock.rgba");

pub const ic_17_shutdown_w: u32 = 64;
pub const ic_17_shutdown_h: u32 = 64;
pub const ic_17_shutdown = @embedFile("ic_17_shutdown.rgba");

pub const ic_18_recycle_bin_full_w: u32 = 64;
pub const ic_18_recycle_bin_full_h: u32 = 64;
pub const ic_18_recycle_bin_full = @embedFile("ic_18_recycle_bin_full.rgba");

pub const ic_19_drive_fixed_w: u32 = 64;
pub const ic_19_drive_fixed_h: u32 = 64;
pub const ic_19_drive_fixed = @embedFile("ic_19_drive_fixed.rgba");

pub const ic_20_drive_removable_w: u32 = 64;
pub const ic_20_drive_removable_h: u32 = 64;
pub const ic_20_drive_removable = @embedFile("ic_20_drive_removable.rgba");

pub const ic_21_drive_optical_w: u32 = 64;
pub const ic_21_drive_optical_h: u32 = 64;
pub const ic_21_drive_optical = @embedFile("ic_21_drive_optical.rgba");

pub const ic_22_printer_w: u32 = 64;
pub const ic_22_printer_h: u32 = 64;
pub const ic_22_printer = @embedFile("ic_22_printer.rgba");

pub const ic_23_info_w: u32 = 64;
pub const ic_23_info_h: u32 = 64;
pub const ic_23_info = @embedFile("ic_23_info.rgba");

pub const ic_24_warning_w: u32 = 64;
pub const ic_24_warning_h: u32 = 64;
pub const ic_24_warning = @embedFile("ic_24_warning.rgba");

pub const ic_25_err_w: u32 = 64;
pub const ic_25_err_h: u32 = 64;
pub const ic_25_err = @embedFile("ic_25_err.rgba");

pub const ic_26_favorites_w: u32 = 64;
pub const ic_26_favorites_h: u32 = 64;
pub const ic_26_favorites = @embedFile("ic_26_favorites.rgba");

pub const ic_27_shell_desktop_w: u32 = 64;
pub const ic_27_shell_desktop_h: u32 = 64;
pub const ic_27_shell_desktop = @embedFile("ic_27_shell_desktop.rgba");

pub const ic_28_downloads_w: u32 = 64;
pub const ic_28_downloads_h: u32 = 64;
pub const ic_28_downloads = @embedFile("ic_28_downloads.rgba");

pub const ic_29_recent_places_w: u32 = 64;
pub const ic_29_recent_places_h: u32 = 64;
pub const ic_29_recent_places = @embedFile("ic_29_recent_places.rgba");

pub const ic_30_library_root_w: u32 = 64;
pub const ic_30_library_root_h: u32 = 64;
pub const ic_30_library_root = @embedFile("ic_30_library_root.rgba");

pub const ic_31_videos_w: u32 = 64;
pub const ic_31_videos_h: u32 = 64;
pub const ic_31_videos = @embedFile("ic_31_videos.rgba");

pub const ic_32_homegroup_w: u32 = 64;
pub const ic_32_homegroup_h: u32 = 64;
pub const ic_32_homegroup = @embedFile("ic_32_homegroup.rgba");

pub const cur_01_arrow_w: u32 = 64;
pub const cur_01_arrow_h: u32 = 64;
pub const cur_01_arrow = @embedFile("cur_01_arrow.rgba");

pub const cur_02_link_w: u32 = 64;
pub const cur_02_link_h: u32 = 64;
pub const cur_02_link = @embedFile("cur_02_link.rgba");

pub const cur_03_text_w: u32 = 64;
pub const cur_03_text_h: u32 = 64;
pub const cur_03_text = @embedFile("cur_03_text.rgba");

pub const cur_04_busy_w: u32 = 64;
pub const cur_04_busy_h: u32 = 64;
pub const cur_04_busy = @embedFile("cur_04_busy.rgba");

pub const cur_05_nesw_w: u32 = 64;
pub const cur_05_nesw_h: u32 = 64;
pub const cur_05_nesw = @embedFile("cur_05_nesw.rgba");

pub const cur_06_ns_w: u32 = 64;
pub const cur_06_ns_h: u32 = 64;
pub const cur_06_ns = @embedFile("cur_06_ns.rgba");

pub const cur_07_ew_w: u32 = 64;
pub const cur_07_ew_h: u32 = 64;
pub const cur_07_ew = @embedFile("cur_07_ew.rgba");

pub const cur_08_move_w: u32 = 64;
pub const cur_08_move_h: u32 = 64;
pub const cur_08_move = @embedFile("cur_08_move.rgba");

pub const cur_09_pen_w: u32 = 64;
pub const cur_09_pen_h: u32 = 64;
pub const cur_09_pen = @embedFile("cur_09_pen.rgba");

pub const cur_10_help_w: u32 = 64;
pub const cur_10_help_h: u32 = 64;
pub const cur_10_help = @embedFile("cur_10_help.rgba");

pub const cur_11_working_w: u32 = 64;
pub const cur_11_working_h: u32 = 64;
pub const cur_11_working = @embedFile("cur_11_working.rgba");

pub const cur_12_unavail_w: u32 = 64;
pub const cur_12_unavail_h: u32 = 64;
pub const cur_12_unavail = @embedFile("cur_12_unavail.rgba");

pub const cur_13_up_w: u32 = 64;
pub const cur_13_up_h: u32 = 64;
pub const cur_13_up = @embedFile("cur_13_up.rgba");

pub const cur_14_nwse_w: u32 = 64;
pub const cur_14_nwse_h: u32 = 64;
pub const cur_14_nwse = @embedFile("cur_14_nwse.rgba");

